INSERT INTO USER(ID, PASSWORD, USERNAME) VALUES(1, 'test1', 'test1');
INSERT INTO USER(ID, PASSWORD, USERNAME) VALUES(2, 'test2', 'test2');
INSERT INTO USER(ID, PASSWORD, USERNAME) VALUES(3, 'test3', 'test3');
INSERT INTO USER(ID, PASSWORD, USERNAME) VALUES(4, 'test4', 'test4');
INSERT INTO USER(ID, PASSWORD, USERNAME) VALUES(5, 'test5', 'test5');