INSERT INTO USER(ID, PASSWORD, USERNAME) VALUES(1, '$2a$10$dHNKIA7qzzmT4JbA8NKaeOV2SvWiHpLu9Tme2vygAX1PYrxvFcJ/S', 'test1');
INSERT INTO USER(ID, PASSWORD, USERNAME) VALUES(2, 'test2', 'test2');
INSERT INTO USER(ID, PASSWORD, USERNAME) VALUES(3, 'test3', 'test3');
INSERT INTO USER(ID, PASSWORD, USERNAME) VALUES(4, 'test4', 'test4');
INSERT INTO USER(ID, PASSWORD, USERNAME) VALUES(5, 'test5', 'test5');


INSERT INTO BOOK_SEARCH_HISTORY(ID, KEYWORD, USER_ID) VALUES(1, '개미', 1);
INSERT INTO BOOK_SEARCH_HISTORY(ID, KEYWORD, USER_ID) VALUES(2, '알고리즘', 1);
INSERT INTO BOOK_SEARCH_HISTORY(ID, KEYWORD, USER_ID) VALUES(3, '어떻게 살것인가', 1);
INSERT INTO BOOK_SEARCH_HISTORY(ID, KEYWORD, USER_ID) VALUES(4, '이것이 리눅스다', 1);
INSERT INTO BOOK_SEARCH_HISTORY(ID, KEYWORD, USER_ID) VALUES(5, '이펙티브 자바', 1);
INSERT INTO BOOK_SEARCH_HISTORY(ID, KEYWORD, USER_ID) VALUES(6, 'JPA프로그래밍', 1);



INSERT INTO BOOKMARK(ID, ISBN, TITLE, USER_ID) VALUES(1, '8932903492', 'JPA프로그래밍', 1);
INSERT INTO BOOKMARK(ID, ISBN, TITLE, USER_ID) VALUES(2, '8956942927', '알고리즘', 1);
INSERT INTO BOOKMARK(ID, ISBN, TITLE, USER_ID) VALUES(3, '115948080X', '개미', 1);
INSERT INTO BOOKMARK(ID, ISBN, TITLE, USER_ID) VALUES(4, '8932917876', '이것이 리눅스다', 1);
INSERT INTO BOOKMARK(ID, ISBN, TITLE, USER_ID) VALUES(5, '1196119589', '어떻게 살것인가', 1);