INSERT INTO USER(ID, PASSWORD, USERNAME) VALUES(1, '$2a$10$dHNKIA7qzzmT4JbA8NKaeOV2SvWiHpLu9Tme2vygAX1PYrxvFcJ/S', 'test1');
INSERT INTO USER(ID, PASSWORD, USERNAME) VALUES(2, 'test2', 'test2');
INSERT INTO USER(ID, PASSWORD, USERNAME) VALUES(3, 'test3', 'test3');
INSERT INTO USER(ID, PASSWORD, USERNAME) VALUES(4, 'test4', 'test4');
INSERT INTO USER(ID, PASSWORD, USERNAME) VALUES(5, 'test5', 'test5');